### ISSUE TITLE
Support for parell computing on PowerPC architecture

### ISSUE THREAD

**Issue by macbury** [paweljw/pvm#1]
We need support for parell computing on my MacMini cluster:
![mac-mini](https://user-images.githubusercontent.com/110908/42724546-b2f64db4-8774-11e8-84fd-638f488865b5.jpg)
![macrack](https://user-images.githubusercontent.com/110908/42724547-b44b38f0-8774-11e8-976f-d111d0f8feb1.png)

**Comment by paweljw** [comment]
Not a problem! Just use `screen` to run the runtime multiple times.

**Comment by macbury** [comment]
What for setup that uses Windows Server?

**Comment by paweljw** [comment]
If you can actually get pvm compiled on Windows Server you probably know the OS-specific way to set up CPU affinity, or if WS has no equivalent to Linux's `taskset`, the OS-specific way of running something like `screen`. :)

**Comment by paweljw** [comment]
.
